### ISSUE TITLE
sap_hana_install: [security] clean up temp files containing credentials

### ISSUE THREAD

**Issue by ja9fuchs** [sap-linuxlab/community.sap_install#149]
https://github.com/sap-linuxlab/community.sap_install/blob/98d21a321b00a39eb4306a0a7a5e93d53518eb5b/roles/sap_hana_install/tasks/main.yml

In the role the file /tmp/SID.info.nw.install is created from template and not cleaned up afterwards.
**The file is world-readable and contains the sidadm user credentials in plain text!**

Please review the requirement of this file (variables are all named "sap_swpm_db_...") in the sap_hana_install role. If not needed for the purpose of this individual role it the related tasks should be removed.
If the file is actually used as part of this role, the role should really make sure the file gets deleted - no matter if the ansible run finishes successfully or not.

Running a cleanup under all circumstances could for instance be accomplished by adding an "always"-block containing that cleanup task at the end of the main.yml.

**Comment by Klaas-** [comment]
I'm guessing the first step should be changing the ACLs of that file: https://github.com/sap-linuxlab/community.sap_install/blob/main/roles/sap_hana_install/tasks/post_install.yml#L49 should be a simple PR :)

**Comment by ja9fuchs** [comment]
This would be a first step to reduce the permissions of the temporary files.

However, in an enterprise environment saving credentials with no security layer should be a no-go by design. If the ansible control node is compromised no password should be retrievable even by a privileged user from any part of the exposed environment.

When using ansible vault to comply with standard security requirements, a user certainly will not expect the critical bit of information to be put into an unencrypted text file at any time of the execution - and on top left over afterwards. :)

**Comment by Klaas-** [comment]
Did you PR the ACL fix? That would be the first step I'd say, this is a community project after all and it makes a fine first PR.

Also I think you misunderstood ansible. As far as I know, at least in temporary files, having credentials, more or less in plain text, will always happen. Because that is how ansible works, it combines all your tasks into python code, copies that python to your target and executes it.

Don't misunderstand me, I do think you're right they should not leave that file on the controller. But with the right ACLs it's not a critical issue anymore.

**Comment by berndfinger** [comment]
A workaround is to skip this task by excluding tag `sap_hana_install_generate_input_file`.
