### ISSUE TITLE
sap_general_preconfigure: firewalld might not be stopped and disabled

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#176]
This can happen if the `firewalld` package is not installed at the time when the role is started. The package facts are gathered at the beginning, in task `Gather package facts` in file `tasks/main.yml`. If the `firewalld` package gets installed later, e.g. in task `Ensure that the required package groups are installed, RHEL 8 and RHEL 9` in file `tasks/RedHat/installation.yml`, then the task `Stop and disable service firewalld` in file `tasks/RedHat/generic/configure-firewall.yml` will be skipped.

**Comment by berndfinger** [comment]
We also could take care of iptables in this context.

**Comment by rhmk** [comment]
Please note: Some customers disable firewalld and use old iptables.service:
```
systemctl status iptables.service
● iptables.service - IPv4 firewall with iptables
   Loaded: loaded (/usr/lib/systemd/system/iptables.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Sun 2022-07-10 18:14:32 CEST; 3 days ago
 Main PID: 2404 (code=exited, status=0/SUCCESS)
```

**Comment by rhmk** [comment]
As we now have the possibility to enable the firewall in sap_hana_install, I would like to add the following variable:

sap_hana_general_preconfigure_enable_firewall (or firewalld)
default value: false

When variable is true, than 
- ensure that firewall is installed
- ensure that firewall is enabled and started

If false we can think of:
- removing firewalld in addition to stopping and disabling

Regading iptables I suggest documenting the following:

This role is handling firewalld only because it is default since RHEL8 and not supported by SAP on RHEL 7. If you want to use iptables please disable firewalld and take care of IP tables handling in part of your playbook
