### ISSUE TITLE
sap_netweaver_preconfigure: use meta/argument_specs.yml for all external variables

### ISSUE THREAD

**Issue by berndfinger** [sap-linuxlab/community.sap_install#321]
See also:
- [specs](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation)
- [example](https://github.com/sap-linuxlab/community.sap_install/blob/59e64f7706a1cb5fa633b2453842fba2f992e9bc/roles/sap_ha_pacemaker_cluster/meta/argument_specs.yml)

**Comment by berndfinger** [comment]
The argument_specs mechanism does not work for variables which are set at run time.

We want to be able to set variable defaults, in some cases based on RHEL versions, and then allow for overriding these defaults by users. Example:
```
sap_netweaver_preconfigure_min_swap_space_mb: "{{ __sap_netweaver_preconfigure_min_swap_space_mb }}"
```
So we could use the opportunity to reduce the amount of run time dependent variables to the absolute minimum.

**Comment by kksat** [comment]
Set at runtime you mean during role execution? Opposite to variables that are set by user before role execution starts? 
I believe you can run module https://docs.ansible.com/ansible/latest/collections/ansible/builtin/validate_argument_spec_module.html
to dynamically to validate arguments that are set during role execution. 

Do you have an example where argument_spec files does not work / fails? I never encountered unreliable behaviour. 

Why setting up default values for variables in `defaults/main.yml` is not an option? These variables can be overwritten by users, or dynamically set during role execution. 

For instance put this is in `defaults/main.yml`

```yaml
min_swap_space_mb_mapping:
   "7": 100
    "8": 200
    "9": 300
min_swap_space_mb: "{{ min_swap_space_mb_mapping[( ansible_facts['major_distribution']| default("7") )]}}"
```
You have to add default because at argument validation ansible facts are not available and validation will fail. 

As all above in defaults file, users can change `min_swap_space_mb` variable

```yaml
- name: Include role
   ansible.builtin.include_role:
      name: role_name
   vars:
      min_swap_space_mb: 150
```

**Comment by berndfinger** [comment]
Here is another example, from role `sap_general_preconfigure`:
For RHEL 7, applicable SAP notes are requiring to set two RHEL kernel parameters: https://github.com/sap-linuxlab/community.sap_install/blob/3300ed080a5db494cf57086ce6139838610ccf4c/roles/sap_general_preconfigure/vars/RedHat_7.yml#L145

For RHEL 9, applicable SAP notes are requiring to set only RHEL kernel parameter `vm.max_map_count`: https://github.com/sap-linuxlab/community.sap_install/blob/75be83b15c0c2cc4b96bfb205af3a44285077d5a/roles/sap_general_preconfigure/vars/RedHat_9.yml#L93

And in file `defaults/main.yml` - https://github.com/sap-linuxlab/community.sap_install/blob/c2727f2f17ed36ceab5eaaf9f0b45ebb1917d35f/roles/sap_general_preconfigure/defaults/main.yml#L88, we are assigning these defaults to a user configurable parameter (so that customers do not have to use the `--extra-vars` functionality to override the internal variable (variables starting with `__`).

**Comment by berndfinger** [comment]
Note: I used the wrong link for `specs` in the initial comment. I have modified it to point to the correct page.
