### ISSUE TITLE
sap*preconfigure: getting error for saptune while running playbook

### ISSUE THREAD

**Issue by vijayshihan** [sap-linuxlab/community.sap_install#400]
I have few questions :
1) How I can resolve saptune. because I do not have license/subscription for SLES for SAP or RHEL for SAP. 
how I can skip this error? can it possible to apply sap notes listed for each solution can be used as workaround? for saptune

2) is there any ansible playbook for saptune? so I can use 

3) is saptune mandatory for sap eco system?

**Comment by berndfinger** [comment]
@vijayshihan There is no saptune available (and not needed) for RHEL for SAP Solutions. But please note that the preconfigure roles for RHEL will attempt to install packages like compat-sap-c++-XX which are only available in RHEL for SAP Solutions, so without this subscription, the role will fail because it does not have access to these packages. Also in the case of RHEL, the RHEL for SAP Solutions subscription is required by SAP when installing SAP ABAP application instances or SAP HANA.

**Comment by vijayshihan** [comment]
Thanks @berndfinger, Still I have queries

1) I have only SLES subscription ( not SLES for SAP subscription). how should I install saptune?
2) Should I download these packages from external site and suppose installed manually. then no issue right?
3) I have RHEL enterprise license ( not RHEL for sap ) and compat-sap-c++-XX package is not available in normal subscription. how I can resolve this issue? should I need download and install from external site?

Thanks in Advance!

**Comment by Klaas-** [comment]
I can answer 3) you need to get the RHEL for SAP Applications or SAP Solutions subscription, I am guessing it's the same for 1)

**Comment by rhmk** [comment]
Hi Vijay,
You can get a free RHEL subscription including the SAP repositories required on developer.redhat.com. The developer subscription comes with all possible add-Ons including HA and SAP repositories.  To get it you have to use a private (non-company) account for that.
You should only use the developer subscription for testing because it doesn't come with production support, so it will not be accepted by SAP if you open a ticket. 
Hope that helps

**Comment by vijayshihan** [comment]
Thanks everyone!

**Comment by berndfinger** [comment]
Closing this issue now, as all questions appear to me as being answered.
