### ISSUE TITLE
sap_swpm: scrambles /etc/hosts

### ISSUE THREAD

**Issue by rhmk** [sap-linuxlab/community.sap_install#63]
For some reason the the update of /etc/hosts fails. After running the role, here is how my  /etc/hosts looks like:

10.103.15.16	rha-nw.rha-nw.c.deft-axon-212715.internal	rha-nw
	rha-hana.rha-nw.c.deft-axon-212715.internal	rha-hana

while it has to be 

10.103.15.16	rha-nw.c.deft-axon-212715.internal	rha-nw
10.103.15.61	rha-hana.c.deft-axon-212715.internal	rha-hana

Investigating where this happens ....

**Comment by rhmk** [comment]
The code that is affected is located here: 
roles/sap_swpm/tasks/pre_install/update_etchosts.yml

maybe we can update this with the code from sap_general_preconfigure

**Comment by rhmk** [comment]
first investigation ansible_fqdn is misunderstood -- use of ansible_domain required. Need to rewoek code for use with sap_ip, sap_domain, sap_hostname.

**Comment by rhmk** [comment]
Variables that need to be reviewed and its usage:
sap_swpm_fqdn:
sap_swpm_set_fqdn: "true"
sap_swpm_db_ip:
sap_swpm_db_fqdn:
sap_swpm_db_host:


sap_swpm_update_etchosts:

**Comment by berndfinger** [comment]
Can you skip modifying /etc/hosts in sap_swpm and just do the modification in sap_general_preconfigure? Or should we modify role sap_general_preconfigure to better support NetWeaver installation?

**Comment by rhmk** [comment]
sap_swpm_fqdn is misused and should be sap_swpm_domain

**Comment by rhmk** [comment]
maybe in different places as well

**Comment by rhmk** [comment]
sap_swpm_fqdn is used in two places: 
1. It sets the variable `NW_getFQDN.FQDN` in the configfile which expects the **domain name**
2. it is used to update the /etc/hosts

It needs to be the domain and not the FQDN, so very misleading usage by SAP

Suggested fix:
- Document this in defaults/main.yml above the variable and the demo playbooks
- run several tests in tasks/pre_install/update_etchosts.yml to ensure the variables are set correctly prior to updating /etc/hosts

please comment

**Comment by berndfinger** [comment]
All hosts on which HANA or NetWeaver is to be installed need to be preconfigured by role sap_general_preconfigure, and all /etc/hosts modification for either one is already performed by role sap_general_preconfigure. So the only remaining action here is to update /etc/hosts with a valid entry for the database host it is different from the current host, right?

**Comment by berndfinger** [comment]
I think we can solve the problem (until we have a new role for setting up `/etc/hosts`) by the following change in `tasks/pre_install/update_etchosts.yml`:

1. Because `sap_swpm_fqdn` is indeed defined in `defaults/main.yml` but with variable type `NoneType`, we replace all `"sap_swpm_fqdn is defined"` by:
`"sap_swpm_fqdn | type_debug != 'NoneType'"`
`"sap_swpm_fqdn | length > 0"`
2. Same for `sap_swpm_db_ip` and `sap_swpm_db_host`
3. Finally, there should be a debug task after each of the two blocks, for warning that despite variable `sap_swpm_update_etchosts` being set to `true`, a desired update to `/etc/hosts` has not been performed because one or more of the conditions in the block had not been met.
This would be something like:
```
- name: SAP SWPM Pre Install - Display warning message in case of no update to '/etc/hosts' for HANA
  ansible.builtin.debug:
    msg: "WARN: '/etc/hosts' was not updated for HANA!"
  when:
    ( sap_swpm_db_ip | type_debug == 'NoneType' ) or
    ( sap_swpm_db_ip | length == 0 ) or
    ( sap_swpm_db_host | type_debug == 'NoneType' ) or
    ( sap_swpm_db_host | length == 0 ) or
    ( sap_swpm_db_host == ansible_hostname )
```
